name: Node.js CI

on:
  pull_request:
    branches: ["master"]

env:
  NODE_VERSION: 16.x
  APP_KEY_ALIAS: ${{ secrets.APP_KEY_ALIAS }}
  APP_STORE_PASSWORD: ${{ secrets.APP_STORE_PASSWOR }}
  APP_KEY_PASSWORD: ${{ secrets.APP_KEY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - run: npm install expo-cli
      - run: yarn
      - run: |
          cd android && ./gradlew assembleRelease
      # - run: yarn test
